name: Publish anibali/pytorch:2.0.1-nocuda-ubuntu22.04

on:
  push:
    branches:
    - master
    paths:
    - dockerfiles/2.0.1-nocuda-ubuntu22.04/*
    - .github/workflows/publish_2.0.1-nocuda-ubuntu22.04.yml
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: anibali/pytorch
        tags: 2.0.1-nocuda-ubuntu22.04,2.0.1-nocuda
        path: dockerfiles/2.0.1-nocuda-ubuntu22.04
